# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
    ]
