# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255, verbose_name='name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment_date')),
            ],
            options={
                'verbose_name': 'article comment',
                'verbose_name_plural': 'article comments',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.IntegerField(verbose_name='order id')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'article'},
        ),
        migrations.AddField(
            model_name='article',
            name='watch_count',
            field=models.IntegerField(default=0, verbose_name='watch count'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='menu_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.MenuItem'),
        ),
    ]
