# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171023_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isshow',
            field=models.BooleanField(default=True, verbose_name='Is Show:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='watch_count',
            field=models.IntegerField(default=0, verbose_name='Watch Count'),
        ),
    ]
