# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171023_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Admin', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editormd',
            field=models.TextField(verbose_name='Editor md'),
        ),
    ]
